<h1>Forside</h1>
<p>
    Velkommen til DIKULANs hjemmeside.
</p>
<p>
    Her på siden kan du bl.a. finde nyttig information om LANet, arrang&oslash;rerne og du kan reservere en plads, så du kan komme til at sidde ved siden af dine venner.
</p>
<h2>Næste dikulan</h2>
<table>
    <tr><td>Starttidspunkt:</td><td>d. 23. april 2010 kl. 16.00</td></tr>
    <tr><td>Sluttidspunkt:</td><td>d. 25. april 2010 kl. 16.00</td></tr>
</table>
