<?php echo '<?'?>xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <title>DIKULAN - The Challenge</title>
        <link media="screen" rel="stylesheet" type="text/css" href="/css/underside/screen.css"/>
        <link media="print" rel="stylesheet" type="text/css" href="/css/underside/print.css"/>
    </head>
    <body>
        <div id="main">
            <div id="top">
                <img alt="" src="/images/page-top.png"/>
            </div>
            <div id="middle">
                <div id="middle-content">                    
                    <ul id="menu">
                        <li class="menu-item"><a href="#">Forside</a></li>
                        <li class="menu-item"><a href="#">Information</a></li>
                        <li class="menu-item"><a href="#">Madmuligheder</a></li>
                        <li class="menu-item"><a href="#">Turneringer/events</a></li>
                        <li class="menu-item"><a href="#">Regler</a></li>
                        <li class="menu-item"><a href="#">Pladsreservation</a></li>
                        <li class="menu-item"><a href="#">Galleri</a></li>
                        <li class="menu-item"><a href="#">Kontakt</a></li>
                        <li class="menu-item"><a href="#">Blog</a></li>
                    </ul>
                    <div id="main-content">
                        <h1>Forside</h1>
                        <p>
                            Velkommen til DIKULANs hjemmeside.
                        </p>
                        <p>
                            Her på siden kan du bl.a. finde nyttig information om LANet, arrang&oslash;rerne og du kan reservere en plads, så du kan komme til at sidde ved siden af dine venner.
                        </p>
                        <h2>Hurtig introduktion</h2>
                        <p>
                            Det n&aelig;ste DIKULAN vil finde sted:
                            <table>
                                <tr><td>Starttidspunkt:</td><td>d. 13. november 2009 kl. 16.00</td></tr>
                                <tr><td>Sluttidspunkt:</td><td>d. 15. november 2009 kl. 16.00</td></tr>
                            </table>
                        </p>
                    </div>
                </div>
            </div>
            <div id="bottom">
                <img id="top" alt="" src="/images/page-bottom.png"/>
            </div>
        </div>
    </body>
</html>