<?php
    $menu = array(
        array('Forside'           , array('controller'=>'index')),
        array('Information'       , array('controller'=>'information')),
        array('Madmuligheder'     , array('controller'=>'food-options')),
        array('Turneringer/events', array('controller'=>'tournaments')),
        array('Regler'            , array('controller'=>'rules')),
        array('Pladsreservation'  , array('controller'=>'seat-booking')),
        array('Galleri'           , array('controller'=>'gallery')),
        array('Kontakt'           , array('controller'=>'contact')),
        array('Nyheder'           , array('controller'=>'news')),
    );
    Zend_Controller_Front::getInstance()->getResponse()->setHeader('Content-type', 'text/html;charset=utf-8');

echo '<?xml version="1.0" encoding="UTF-8"?>'
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <title>DIKULAN - The Challenge</title>
        <link media="screen" rel="stylesheet" type="text/css" href="/css/underside/screen.css"/>
        <link media="print" rel="stylesheet" type="text/css" href="/css/underside/print.css"/>
    </head>
    <body>
        <div id="main">
            <div id="top">
                <img alt="" src="/images/page-top.png"/>
            </div>
            <div id="middle">
                <div id="middle-content">                    
                    <ul id="menu">
                        <li class="menu-item">
                        <?php foreach($menu as $item): ?>
                            <a href="<?php echo $this->url($item[1], null, true)?>">
                                <?php echo $item[0] ?>
                            </a>
                        <?php endforeach; ?>
                        </li>
                    </ul>
                    <div id="main-content">
                        <?php echo $this->layout()->content ?>
                    </div>
                </div>
            </div>
            <div id="bottom">
                <img id="top" alt="" src="/images/page-bottom.png"/>
            </div>
        </div>
    </body>
</html>